server:
  port: 7474


#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: ribbon-application
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.125.60:8848

