server:
  port: 10010

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8965/
          predicates:
          - Path=/produce/get