server:
  # 启动两个main函数，一个是8965，一个是8964
  port: 8964

spring:
  application:
    name: ribbon-produce
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos

      config:
        server-addr: 127.0.0.1:8848

java1234:
  name: 1111
  age: 123
