server:
  port: 10086

spring:
  application:
    name: ribbon-eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

    #关掉，自己是server向自己注册
    register-with-eureka: false
